export { register } from "./authentication/register.js"
export { login } from "./authentication/login.js"
export { updateEmail } from "./authentication/updateEmail.js"
export { updatePassword } from "./authentication/updatePassword.js"
export { verifyOtp } from "./authentication/verifyOtp.js"
export { userAuthentic } from "./authentication/userAuthentic.js"
export { logout } from "./authentication/logout.js"
export { resendOtp } from "./authentication/resendOtp.js"
export { resetPasswordEmailVerify } from "./authentication/resetPasswordEmailVerify.js"
export { resetPassword } from "./authentication/resetPassword.js"

export { createPlayer } from "./players/createPlayer.js"
export { playerAuthentic } from "./players/playerAuthentic.js"
export { editPlayer } from "./players/editPlayer.js"
export { getPlayer } from "./Players/getPlayer.js"

export { createTeam } from "./teams/createTeam.js"
export { addPlayer } from "./teams/addPlayer.js"
export { myTeams } from "./teams/myTeams.js"
export { opponentsTeam } from "./teams/opponentsTeam.js"
export { removePlayer } from "./teams/removePlayer.js"
export { leftTeam } from "./teams/leftTeam.js"
export { getTeam } from "./teams/getTeam.js"
export { deleteTeam } from "./teams/deleteTeam.js"

export { search } from "./search.js"

export {createMatch} from "./matches/createMatch.js"
export {getMatch} from "./matches/getMatch.js"
export {getMatches} from "./matches/getMatches.js"
export {getMyMatches, sendMyMatches} from "./matches/myMatches.js"