export { register } from "./authentication/register"
export { login } from "./authentication/login"
export { updateEmail } from "./authentication/updateEmail"
export { updatePassword } from "./authentication/updatePassword"
export { verifyOtp } from "./authentication/verifyOtp"
export { userAuthentic } from "./authentication/userAuthentic"
export { logout } from "./authentication/logout"
export { resendOtp } from "./authentication/resendOtp"
export { resetPasswordEmailVerify } from "./authentication/resetPasswordEmailVerify"
export { resetPassword } from "./authentication/resetPassword"

export { createPlayer } from "./players/createPlayer"
export { playerAuthentic } from "./players/playerAuthentic"
export { editPlayer } from "./players/editPlayer"
export { getPlayer } from "./Players/getPlayer"

export { createTeam } from "./teams/createTeam"
export { addPlayer } from "./teams/addPlayer"
export { myTeams } from "./teams/myTeams"
export { opponentsTeam } from "./teams/opponentsTeam"
export { removePlayer } from "./teams/removePlayer"
export { leftTeam } from "./teams/leftTeam"
export { getTeam } from "./teams/getTeam"
export { deleteTeam } from "./teams/deleteTeam"

export { search } from "./search"

export {createMatch} from "./matches/createMatch"
export {getMatch} from "./matches/getMatch"
export {getMatches} from "./matches/getMatches"
export {getMyMatches, sendMyMatches} from "./matches/myMatches"