export { register } from "./authentication/register"
export { login } from "./authentication/login"
export { updateEmail } from "./authentication/updateEmail"
export { updatePassword } from "./authentication/updatePassword"
export { verifyOtp } from "./authentication/verifyOtp"
export { userAuthentic } from "./authentication/userAuthentic"
export { logout } from "./authentication/logout"
export { resendOtp } from "./authentication/resendOtp"

export { createPlayer } from "./players/createPlayer"
export { playerAuthentic } from "./players/playerAuthentic"
export { createTeam } from "./teams/createTeam"
export { addPlayer } from "./teams/addPlayer"
export { myTeams } from "./teams/myTeams"
export { removePlayer } from "./teams/removePlayer"
export { leftTeam } from "./teams/leftTeam"
export { getTeam } from "./teams/getTeam"

export { search } from "./search"

export {createMatch} from "./matches/createMatch"
export {getMatch} from "./matches/getMatch"
export {myMatches} from "./matches/myMatches"